### ISSUE TITLE
Can you provide versions of HG38 and T2T in the ‘How to Use’ Chapter?

### ISSUE THREAD

**Issue by cherryamme** [SoloEdward/HgvsGo#1]
Can you provide versions of HG38 and T2T in the ‘How to Use’ Chapter?

**Comment by SoloEdward** [comment]
HgvsGo has introduced support for the hg38 and T2T genomes. However, please note that it has not been extensively tested. The ReadMe file has been updated, and we encourage you to refer to the latest version for instructions on running HgvsGo.
